### ISSUE TITLE
ARP

### ISSUE THREAD

**Issue by SamNapa** [takayuki/lwip-tap#2]
Hi,
I met an issue trying to enable DEBUG mode "configure --enable-debug" doesn't work. 

Ps: I'm trying to read lwIP's arp table  does someone already did it ? 

Sam

**Comment by Nable80** [comment]
Hi,
DEBUG mode does work but you should add ``-d`` when running binary, see the following lines: https://github.com/takayuki/lwip-tap/blob/master/lwip-tap.c#L206

Without ``--enable-debug`` all debug prints are stripped from source but you also need to set LWIP_DBG_* flags to enable different kinds of messages, ``-d`` switch sets a lot of them and you may want to disable some.
Btw, this repo seems to be abandoned. I was maintaining a private fork (with the up-to-date lwIP and some fixes) and now I'm trying to find some time to properly publish it.

Speaking about reading ARP, I remember that it is used in SNMP server code but I don't remember exact details now. You may try reading lwIP sources and examples from the main lwIP repo (see apps folder) and lwip-contrib. You can use ``grep`` to find interesting parts quickly.

**Comment by SamNapa** [comment]
Thank you for your answer.  For the debuging I added 

"#define LWIP_DEBUG 1

#define IP_DEBUG        LWIP_DBG_ON"

on lwipost.h  and it worked but for arp I really don't understand how it works with TAP. When I listen with wireshark I don't see any arp's requests or answers from lwIP. 

You suggest to emit a snmp request to see the lwIP's arp table ?

**Comment by Nable80** [comment]
There's no need to edit any files to turn on debugging. Just configure with ``--enable-debug`` and run with ``-d``, e.g.: ``sudo ./lwip-tap -d -H -i addr=172.16.0.2,netmask=255.255.255.0,gw=172.16.0.1``
If it produces too verbose output, you can change lines 208-209 in lwip-tap.c to disable some types of debug messages.

> but for arp I really don't understand how it works with TAP

It just works the same way as it would with any ethernet-like interface: platform specific function fetches next packet (see tapif_thread and tapif_input functions in https://github.com/takayuki/lwip-tap/blob/master/tapif.c), allocates memory for it (low_level_input) and passes it to lwIP packet parser (``netif->input(p, netif)`` - https://github.com/takayuki/lwip-tap/blob/master/tapif.c#L374), if incoming packet is correct, parser updates ARP tables and if it was an ARP request - it emits a response: https://git.savannah.nongnu.org/cgit/lwip.git/tree/src/core/ipv4/etharp.c#n706

> When I listen with wireshark I don't see any arp's requests or answers from lwIP.

Did you try pinging the IP address of your lwip-tap instance? It won't emit ARP packets if no one asks for it.

> You suggest to emit a snmp request to see the lwIP's arp table ?

You can do it. But I was suggesting to read the code of lwIP's SNMP server, it contains a good example of reading lwIP's ARP table: https://git.savannah.nongnu.org/cgit/lwip.git/tree/src/apps/snmp/snmp_mib2_ip.c#n484

**Comment by SamNapa** [comment]
Ths for your answer. May I ask you a last question ? 
I want to add new source code to lwIP. What do I have to change in configuration files ?

**Comment by Nable80** [comment]
> May I ask you a last question?

You can ask more questions, there's no problem if they are related to topic.
> I want to add new source code to lwIP.

What do yo mean? After cloning this repo with ``--recursive`` option you'll have the full source code tree and it's possible to modify local files in ``lwip/`` sub-folder too. Of course, it's better to leave lwIP code as-is and to add your code in other files: either in main file ``lwip-tap.c`` or in some new file, just don't forget to add paths of added files in ``Makefile.in``, see ``SOURCES`` variable: https://github.com/takayuki/lwip-tap/blob/cafd907d99fe1403f6be3574492bfda170cdb6d0/Makefile.in#L43

**Comment by SamNapa** [comment]
Thank you 
Yeah I added a new source code "secure.c" in /lwip/src/core 

I  added lwip/src/core/secure.c \ in Makefile.in 

The compilation is ok but when I want to "make" I have this error : 

"gcc: fatal error: no input files
compilation terminated.
Makefile:94 : recipe for target  « secure.o » failed
make: *** [secure.o] Error 1  "

Did I forgot something ?

**Comment by Nable80** [comment]
> I added lwip/src/core/secure.c \ in Makefile.in

Don't forget that Make is very sensitive to subtle white-space variations: tabs and spaces have different meaning, there are places where white-space is required and there are places where it should be zero space characters. Could you post your edited Makefile somewhere? e.g. https://gist.github.com/

**Comment by SamNapa** [comment]
I checked that and I don't think that the probleme come from here 
But here is the makefile.in
https://gist.github.com/SamNapa/febaa1688355dd67fcdb8685892990f2
(I added my file line 63)

**Comment by Nable80** [comment]
OK. Then you should run ``./configure`` to generate ``Makefile``. Which options do you use for ``configure``? If configuration step completes successfully, then you should run ``make depend`` and then ``make``.

**Comment by SamNapa** [comment]
Make depend saved my day :) thank you so much

**Comment by Nable80** [comment]
Oh, I'm happy to hear it helped!
Btw, is your initial issue with reading ARP tables resolved?
Don't forget to close the issue here when it's done.

**Comment by SamNapa** [comment]
Oh yes and thank you :)
